name = "cf-r2-webdav"
main = "src/index.ts"
compatibility_date = "2023-01-01"

[vars]
USERNAME = "cfwebdav"
PASSWORD = "cf123webdav654"
BUCKET_NAME = "cf-webdav"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cf-webdav"